import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Bolt, Download, Leaf, Timer, TriangleAlert } from "lucide-react";
import { EnergyChart } from "@/components/energy-chart";
import { MetricCard, Panel, SectionHeading } from "@/components/ui";
import { energyByZone } from "@/lib/mockData";

export default function AnalyticsPage() {
  const wasteZones = energyByZone.filter((zone) => zone.occupancy < 2 && zone.energy > 50);
  return <div className="space-y-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 text-[10px] font-medium uppercase tracking-[0.19em] text-slate-500">Performance intelligence <span className="mx-1.5 text-slate-700">/</span> Energy</div><h1 className="text-[25px] font-semibold tracking-tight text-slate-50 sm:text-[29px]">Cost & energy optimization</h1><p className="mt-1.5 text-xs text-slate-500">Understand energy use against occupied production time.</p></div><button className="flex items-center gap-2 rounded-lg border border-white/[0.08] bg-[#0e141b] px-3 py-2 text-[10px] text-slate-300 hover:bg-white/[0.04]"><Download size={13}/> Export report</button></div>
    <div className="flex flex-wrap items-center gap-2"><button className="rounded-lg border border-cyan-300/20 bg-cyan-300/[0.08] px-3 py-2 text-[10px] font-medium text-cyan-200">Today · Shift A</button><button className="rounded-lg border border-white/[0.07] bg-[#0e141b] px-3 py-2 text-[10px] text-slate-500">Last 7 days</button><button className="rounded-lg border border-white/[0.07] bg-[#0e141b] px-3 py-2 text-[10px] text-slate-500">Last 30 days</button><div className="ml-auto hidden text-[9px] text-slate-600 sm:block">UPDATED 14:32 WIB</div></div>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Energy consumed" value="761" unit="kWh" delta="↓ 4.2%" hint="vs. previous shift" icon={Bolt} tone="cyan"/><MetricCard label="Occupied time" value="36.8" unit="hrs" delta="↑ 2.6%" hint="across all zones" icon={Timer} tone="green"/><MetricCard label="Unoccupied waste" value="136" unit="kWh" delta="17.9%" hint="of total consumption" icon={TriangleAlert} tone="amber"/><MetricCard label="Estimated savings" value="$218" delta="↑ 12.4%" hint="this month" icon={Leaf} tone="green"/></div>
    <Panel className="p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><SectionHeading eyebrow="Consumption analysis" title="Energy vs. occupancy by zone" detail="High consumption during low occupancy may signal avoidable energy waste."/><div className="rounded-lg border border-amber-300/10 bg-amber-300/[0.05] px-3 py-2 text-[9px] text-amber-200"><span className="mr-1.5 text-amber-300">●</span>{wasteZones.length} zones flagged for review</div></div><EnergyChart/><div className="mt-1 flex flex-wrap items-center gap-4 border-t border-white/[0.06] pt-3 text-[9px] text-slate-600"><span>ENERGY CONSUMPTION · KWH</span><span>OCCUPANCY TIME · HOURS</span><span className="ml-auto">SHIFT A · 06:00–14:00</span></div></Panel>
    <Panel><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.06] px-5 py-4"><SectionHeading eyebrow="Optimization opportunities" title="Zones to investigate" detail="High energy draw while utilization is low."/><Link href="/events" className="text-[10px] text-cyan-300 hover:text-cyan-200">Create work order →</Link></div><div className="divide-y divide-white/[0.045]">{wasteZones.map((zone) => <div key={zone.zone} className="flex flex-wrap items-center gap-4 px-5 py-3.5"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-amber-300/[0.08] text-amber-300"><TriangleAlert size={14}/></div><div className="min-w-[130px] flex-1"><div className="text-xs font-medium text-slate-200">{zone.zone}</div><div className="mt-0.5 text-[9px] text-slate-500">{zone.occupancy} hrs occupied this shift</div></div><div className="text-right"><div className="font-mono text-xs text-slate-300">{zone.energy} <span className="text-[9px] text-slate-600">kWh</span></div><div className="mt-0.5 text-[9px] text-amber-400">{Math.round(zone.energy / 8)} kWh avg. during idle</div></div><div className="hidden w-24 sm:block"><div className="h-1 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-amber-400" style={{width:`${Math.min(100, zone.energy / 2)}%`}}/></div></div><ArrowDownRight size={14} className="text-amber-400"/></div>)}</div></Panel>
    <p className="text-[9px] text-slate-600">Savings are estimates based on historical shift averages. <span className="ml-1 text-slate-700">Operational data refreshed every 60 seconds.</span></p>
  </div>;
}
