"use client";

import { Camera, Maximize2, Radio, X } from "lucide-react";
import { zoneName, type FacilityEvent } from "@/lib/mockData";

export function CameraView({ event, onClose }: { event: FacilityEvent | null; onClose: () => void }) {
  if (!event?.hasCctv) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm" onClick={onClose}><section role="dialog" aria-modal="true" aria-labelledby="camera-title" onClick={(click) => click.stopPropagation()} className="w-full max-w-3xl overflow-hidden rounded-2xl border border-white/10 bg-[#0e141b] shadow-2xl"><header className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div><div className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[0.18em] text-cyan-300"><Camera size={12}/> CCTV · {zoneName(event.zoneId)}</div><h2 id="camera-title" className="mt-1 text-sm font-semibold text-slate-100">{event.id} camera feed</h2></div><button aria-label="Close camera" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-white/[0.05] hover:text-white"><X size={16}/></button></header><div className="relative aspect-video overflow-hidden bg-[#070b10]" style={{ backgroundImage: "linear-gradient(rgba(20,40,39,.2) 1px, transparent 1px),linear-gradient(90deg,rgba(20,40,39,.2) 1px,transparent 1px),radial-gradient(ellipse at 52% 70%,#263a3a 0,#111c20 45%,#080d12 80%)", backgroundSize: "24px 24px,24px 24px,auto" }}><div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black/40"/><div className="absolute left-[19%] top-[24%] h-[62%] w-[28%] border border-emerald-300/20 bg-emerald-300/[0.035]"/><div className="absolute left-[54%] top-[33%] h-[52%] w-[25%] border border-cyan-300/20 bg-cyan-300/[0.025]"/><div className="absolute left-[28%] top-[47%] h-[18%] w-[13%] border border-rose-400/80"><span className="absolute -top-5 left-0 bg-rose-500 px-1.5 py-0.5 font-mono text-[8px] text-white">ALERT ZONE</span></div><div className="absolute inset-x-0 top-0 flex justify-between p-4 font-mono text-[9px] text-white/60"><span>CAM-{event.zoneId}-01 · 1080P</span><span>29 SEP 2026</span></div><div className="absolute bottom-4 left-4 flex items-center gap-2 rounded-md bg-black/50 px-2.5 py-1.5 font-mono text-[9px] text-slate-300"><Radio size={11} className="text-rose-400"/> LIVE · SIMULATED CCTV</div><Maximize2 size={13} className="absolute bottom-5 right-5 text-white/60"/></div><footer className="flex flex-wrap items-center justify-between gap-2 px-5 py-3 text-[9px] text-slate-500"><span>{event.description}</span><span>Feed simulation · 24 FPS</span></footer></section></div>;
}
