"use client";

import { Activity, ArrowDownRight, Camera, CircleAlert, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { zoneName, type FacilityEvent } from "@/lib/mockData";

function formatTime(value: string) {
  return new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Jakarta", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value));
}

export function EventTimeline({ events, selectedId, onSelect }: { events: FacilityEvent[]; selectedId?: string; onSelect: (event: FacilityEvent) => void }) {
  const [query, setQuery] = useState("");
  const visible = useMemo(() => events.filter((event) => `${event.id} ${event.description} ${zoneName(event.zoneId)} ${event.type}`.toLowerCase().includes(query.toLowerCase())), [events, query]);
  return <section className="overflow-hidden rounded-xl border border-white/[0.07] bg-[#0e141b]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.06] px-5 py-4"><div><div className="text-[9px] font-semibold uppercase tracking-[0.2em] text-cyan-400/80">Live facility log</div><h2 className="mt-1 text-[15px] font-semibold text-slate-100">Event timeline</h2><p className="mt-1 text-[10px] text-slate-500">Select an event to inspect and take action.</p></div><label className="relative"><Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-600"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search events" className="w-36 rounded-lg border border-white/[0.08] bg-[#090d12] py-2 pl-8 pr-3 text-[10px] text-slate-300 outline-none placeholder:text-slate-600 focus:border-cyan-300/30 sm:w-44"/></label></div><div className="max-h-[640px] divide-y divide-white/[0.045] overflow-y-auto">{visible.map((event) => { const alarm = event.type === "Alarm"; const warning = event.type === "Warning"; const Icon = alarm ? CircleAlert : warning ? ArrowDownRight : Activity; return <button key={event.id} onClick={() => onSelect(event)} className={`flex w-full gap-3 px-5 py-4 text-left transition hover:bg-white/[0.025] ${selectedId === event.id ? "bg-cyan-300/[0.045]" : ""}`}><span className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${alarm ? "bg-rose-400/10 text-rose-300" : warning ? "bg-amber-400/10 text-amber-300" : "bg-cyan-400/10 text-cyan-300"}`}><Icon size={14}/></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center justify-between gap-2"><span className={`rounded-full border px-2 py-0.5 text-[8px] ${alarm ? "border-rose-400/15 bg-rose-400/[0.07] text-rose-300" : warning ? "border-amber-400/15 bg-amber-400/[0.07] text-amber-300" : "border-cyan-400/15 bg-cyan-400/[0.07] text-cyan-300"}`}>{event.type}</span><time className="font-mono text-[9px] text-slate-600">{formatTime(event.timestamp)} WIB</time></span><span className="mt-2 block text-[11px] leading-relaxed text-slate-300">{event.description}</span><span className="mt-1.5 flex items-center gap-2 text-[9px] text-slate-600">{zoneName(event.zoneId)}<span>·</span>{event.id}<span className={`ml-auto ${event.resolutionStatus === "Open" ? "text-rose-300" : "text-emerald-300"}`}>{event.resolutionStatus}</span>{event.hasCctv && <Camera size={11} className="text-cyan-300"/>}</span></span></button>; })}{visible.length === 0 && <div className="py-10 text-center text-xs text-slate-500">No matching events.</div>}</div><div className="border-t border-white/[0.06] px-5 py-3 text-[9px] text-slate-600">Showing {visible.length} of {events.length} events</div></section>;
}
