"use client";

import { useMemo, useState } from "react";
import { Camera, Check, ChevronDown, ClipboardList, ExternalLink, FileText, Filter, Search, X } from "lucide-react";
import { events as seedEvents, zoneName, type FacilityEvent } from "@/lib/mockData";
import { Panel, SectionHeading, StatusPill } from "@/components/ui";

function formatTime(value: string) { return new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Jakarta", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)); }

export default function EventsPage() {
  const [rows, setRows] = useState<FacilityEvent[]>(seedEvents);
  const [selected, setSelected] = useState<FacilityEvent | null>(null);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All events");
  const [cause, setCause] = useState("");
  const [followUp, setFollowUp] = useState("");
  const [saved, setSaved] = useState(false);
  const filtered = useMemo(() => rows.filter((event) => (filter === "All events" || (filter === "Open only" ? event.resolutionStatus === "Open" : event.type === filter)) && `${event.id} ${event.description} ${zoneName(event.zoneId)}`.toLowerCase().includes(query.toLowerCase())), [rows, filter, query]);
  const saveWorkOrder = () => {
    if (!selected || !cause.trim() || !followUp.trim()) return;
    setRows((current) => current.map((event) => event.id === selected.id ? { ...event, resolutionStatus: "Resolved", actionNote: `Penyebab: ${cause.trim()} · Tindak lanjut: ${followUp.trim()}` } : event));
    setSaved(true);
  };
  const openForm = (event: FacilityEvent) => { setSelected(event); setCause(""); setFollowUp(""); setSaved(false); };
  return <div className="space-y-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 text-[10px] font-medium uppercase tracking-[0.19em] text-slate-500">Operations <span className="mx-1.5 text-slate-700">/</span> Event management</div><h1 className="text-[25px] font-semibold tracking-tight text-slate-50 sm:text-[29px]">Events & work orders</h1><p className="mt-1.5 text-xs text-slate-500">Review facility activity and document corrective actions.</p></div><button onClick={() => setFilter(filter === "Open only" ? "All events" : "Open only")} className="flex items-center gap-2 rounded-lg border border-white/[0.08] bg-[#0e141b] px-3 py-2 text-[10px] text-slate-300 hover:bg-white/[0.04]"><Filter size={13}/>{filter === "Open only" ? "Showing open" : "Filter events"}<ChevronDown size={12}/></button></div>
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/[0.07] bg-[#0e141b] p-4"><div className="text-[9px] uppercase tracking-[0.15em] text-slate-500">Events today</div><div className="mt-2 text-xl font-semibold">{rows.length.toString().padStart(2,"0")}<span className="ml-2 text-[10px] font-normal text-slate-600">recorded</span></div></div><div className="rounded-xl border border-rose-400/10 bg-[#0e141b] p-4"><div className="text-[9px] uppercase tracking-[0.15em] text-slate-500">Open actions</div><div className="mt-2 text-xl font-semibold text-rose-200">{rows.filter((e)=>e.resolutionStatus==="Open").length.toString().padStart(2,"0")}<span className="ml-2 text-[10px] font-normal text-slate-600">awaiting resolution</span></div></div><div className="rounded-xl border border-white/[0.07] bg-[#0e141b] p-4"><div className="text-[9px] uppercase tracking-[0.15em] text-slate-500">Resolved today</div><div className="mt-2 text-xl font-semibold text-emerald-200">{rows.filter((e)=>e.resolutionStatus==="Resolved").length.toString().padStart(2,"0")}<span className="ml-2 text-[10px] font-normal text-slate-600">work orders closed</span></div></div></div>
    <Panel className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.06] px-5 py-4"><SectionHeading eyebrow="Facility log" title="Event timeline" detail="Sensor alerts, operations updates, and corrective work."/><div className="relative"><Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-600"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search events..." className="w-44 rounded-lg border border-white/[0.08] bg-[#090d12] py-2 pl-8 pr-3 text-[10px] text-slate-300 outline-none placeholder:text-slate-600 focus:border-cyan-300/30"/></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead><tr className="border-b border-white/[0.06] text-[9px] font-medium uppercase tracking-[0.14em] text-slate-600"><th className="px-5 py-3">Time</th><th className="px-4 py-3">Zone</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Description</th><th className="px-4 py-3">CCTV</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-white/[0.045]">{filtered.map((event)=><tr key={event.id} className="transition hover:bg-white/[0.018]"><td className="whitespace-nowrap px-5 py-4"><div className="font-mono text-[10px] text-slate-300">{formatTime(event.timestamp)}</div><div className="mt-1 font-mono text-[9px] text-slate-600">{event.id}</div></td><td className="whitespace-nowrap px-4 py-4"><div className="text-[11px] text-slate-300">{zoneName(event.zoneId)}</div><div className="mt-1 font-mono text-[9px] text-slate-600">{event.zoneId}</div></td><td className="px-4 py-4"><StatusPill value={event.type}/></td><td className="max-w-[330px] px-4 py-4"><div className="truncate text-[11px] text-slate-300">{event.description}</div>{event.actionNote&&<div className="mt-1 flex items-center gap-1 text-[9px] text-slate-600"><FileText size={10}/>{event.actionNote}</div>}</td><td className="px-4 py-4">{event.hasCctv?<button className="flex items-center gap-1.5 text-[10px] text-cyan-300 hover:text-cyan-200"><Camera size={13}/>View<ExternalLink size={10}/></button>:<span className="text-[10px] text-slate-700">—</span>}</td><td className="px-4 py-4"><StatusPill value={event.resolutionStatus}/></td><td className="px-5 py-4 text-right">{event.resolutionStatus==="Open"?<button onClick={()=>openForm(event)} className="rounded-md border border-cyan-300/15 bg-cyan-300/[0.07] px-2.5 py-1.5 text-[9px] font-medium text-cyan-200 hover:bg-cyan-300/[0.13]">Create work order</button>:<button onClick={()=>openForm(event)} className="text-[9px] text-slate-500 hover:text-slate-300">View details</button>}</td></tr>)}</tbody></table>{filtered.length===0&&<div className="py-12 text-center text-xs text-slate-500">No events match your search.</div>}</div>
      <div className="flex items-center justify-between border-t border-white/[0.06] px-5 py-3 text-[9px] text-slate-600"><span>Showing {filtered.length} of {rows.length} events</span><div className="flex gap-1"><button className="rounded border border-white/[0.07] px-2 py-1 text-slate-500">‹</button><button className="rounded border border-cyan-300/20 bg-cyan-300/[0.08] px-2 py-1 text-cyan-200">1</button><button className="rounded border border-white/[0.07] px-2 py-1 text-slate-500">›</button></div></div>
    </Panel>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#10171f] shadow-2xl"><div className="flex items-start justify-between border-b border-white/[0.07] p-5"><div><div className="mb-2 flex items-center gap-2"><StatusPill value={selected.type}/><span className="font-mono text-[9px] text-slate-600">{selected.id}</span></div><h2 className="text-sm font-semibold">{saved?"Work order saved":"Create work order"}</h2><p className="mt-1 max-w-sm text-[10px] leading-relaxed text-slate-500">{selected.description} · {zoneName(selected.zoneId)}</p></div><button onClick={()=>setSelected(null)} className="rounded-lg p-1.5 text-slate-500 hover:bg-white/5 hover:text-slate-200"><X size={16}/></button></div>
      {saved?<div className="p-5"><div className="flex items-start gap-3 rounded-xl border border-emerald-400/15 bg-emerald-400/[0.05] p-4"><div className="rounded-full bg-emerald-400/10 p-1.5 text-emerald-300"><Check size={14}/></div><div><div className="text-xs font-medium text-emerald-200">Corrective action recorded</div><div className="mt-1 text-[10px] leading-relaxed text-slate-400">Event marked resolved and the work order has been attached to the event log.</div></div></div><button onClick={()=>setSelected(null)} className="mt-5 w-full rounded-lg bg-cyan-300 py-2.5 text-[10px] font-semibold text-slate-950 hover:bg-cyan-200">Done</button></div>:<div className="space-y-4 p-5"><div><label htmlFor="cause" className="mb-1.5 block text-[10px] font-medium text-slate-300">Penyebab <span className="text-rose-300">*</span></label><textarea id="cause" value={cause} onChange={(e)=>setCause(e.target.value)} rows={3} placeholder="Describe the root cause..." className="w-full resize-none rounded-lg border border-white/[0.08] bg-[#090d12] px-3 py-2.5 text-[11px] text-slate-200 outline-none placeholder:text-slate-600 focus:border-cyan-300/30"/></div><div><label htmlFor="follow-up" className="mb-1.5 block text-[10px] font-medium text-slate-300">Tindak Lanjut <span className="text-rose-300">*</span></label><textarea id="follow-up" value={followUp} onChange={(e)=>setFollowUp(e.target.value)} rows={3} placeholder="Document the corrective action taken..." className="w-full resize-none rounded-lg border border-white/[0.08] bg-[#090d12] px-3 py-2.5 text-[11px] text-slate-200 outline-none placeholder:text-slate-600 focus:border-cyan-300/30"/></div><div className="flex items-center gap-2 rounded-lg border border-white/[0.05] bg-white/[0.02] p-3 text-[9px] text-slate-500"><ClipboardList size={13} className="text-cyan-300"/>This work order will be attached to {selected.id} and update its status.</div><div className="flex justify-end gap-2 pt-1"><button onClick={()=>setSelected(null)} className="rounded-lg border border-white/[0.08] px-3 py-2 text-[10px] text-slate-400 hover:bg-white/[0.04]">Cancel</button><button disabled={!cause.trim()||!followUp.trim()} onClick={saveWorkOrder} className="rounded-lg bg-cyan-300 px-4 py-2 text-[10px] font-semibold text-slate-950 hover:bg-cyan-200 disabled:cursor-not-allowed disabled:opacity-40">Save work order</button></div></div>}</div></div>}
  </div>;
}
