import { ArrowRight, Check, Clock3 } from "lucide-react";

const batches = [
  { time: "08:00", end: "10:30", id: "B-2408", product: "Housing assembly · Series A", target: "2,400 units", status: "Complete" },
  { time: "10:30", end: "13:00", id: "B-2409", product: "Control module · Series C", target: "1,800 units", status: "In progress" },
  { time: "13:00", end: "15:30", id: "B-2410", product: "Pump casing · Series B", target: "2,100 units", status: "Upcoming" },
  { time: "15:30", end: "18:00", id: "B-2411", product: "Housing assembly · Series A", target: "2,400 units", status: "Upcoming" },
];
export function ProductionSchedule() {
  return <section className="rounded-xl border border-white/[0.07] bg-[#0e141b]"><div className="flex items-center justify-between border-b border-white/[0.06] px-5 py-4"><div><div className="text-[9px] font-semibold uppercase tracking-[0.2em] text-cyan-400/80">Shift A · 06:00–18:00</div><h2 className="mt-1 text-[15px] font-semibold text-slate-100">Production schedule</h2></div><span className="flex items-center gap-1.5 rounded-lg border border-white/[0.07] bg-white/[0.02] px-2.5 py-1.5 text-[9px] text-slate-400"><Clock3 size={12}/> Today</span></div><div className="px-5 py-1">{batches.map((batch) => { const current = batch.status === "In progress"; const done = batch.status === "Complete"; return <article key={batch.id} className="relative flex gap-4 py-4"><div className="flex w-12 shrink-0 flex-col items-center"><span className={`z-10 flex h-6 w-6 items-center justify-center rounded-full border ${current ? "border-cyan-300/30 bg-cyan-300/10 text-cyan-300" : done ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : "border-white/10 bg-[#0e141b] text-slate-600"}`}>{done ? <Check size={12}/> : <span className="h-1.5 w-1.5 rounded-full bg-current"/>}</span>{batch.id !== "B-2411" && <span className={`absolute left-[23px] top-10 h-[calc(100%-1.5rem)] w-px ${done ? "bg-emerald-400/20" : "bg-white/[0.07]"}`}/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-x-2 gap-y-1"><div className="font-mono text-[10px] text-slate-300">{batch.time}<span className="mx-1.5 text-slate-700">—</span>{batch.end}</div><span className={`text-[8px] uppercase tracking-wider ${current ? "text-cyan-300" : done ? "text-emerald-300" : "text-slate-600"}`}>{batch.status}</span></div><h3 className="mt-2 truncate text-[11px] font-medium text-slate-200">{batch.product}</h3><div className="mt-1 flex items-center justify-between text-[9px] text-slate-500"><span>{batch.id}</span><span>{batch.target}</span></div>{current && <div className="mt-3 h-1 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full w-[62%] rounded-full bg-cyan-400"/></div>}</div></article>; })}</div><button className="flex w-full items-center justify-center gap-1.5 border-t border-white/[0.06] py-3 text-[9px] text-slate-500 transition hover:text-cyan-300">View full schedule <ArrowRight size={12}/></button></section>;
}
